'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.18444
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Teal")>  _
        Public Property Couleur_Font() As Global.System.Drawing.Color
            Get
                Return CType(Me("Couleur_Font"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Couleur_Font") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("17")>  _
        Public Property Compteur_image() As Integer
            Get
                Return CType(Me("Compteur_image"),Integer)
            End Get
            Set
                Me("Compteur_image") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Compteur_Groupe() As Integer
            Get
                Return CType(Me("Compteur_Groupe"),Integer)
            End Get
            Set
                Me("Compteur_Groupe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Size_Location_Image_centrale() As String
            Get
                Return CType(Me("Size_Location_Image_centrale"),String)
            End Get
            Set
                Me("Size_Location_Image_centrale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Chemin_Image_Centrale() As String
            Get
                Return CType(Me("Chemin_Image_Centrale"),String)
            End Get
            Set
                Me("Chemin_Image_Centrale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Chemin_Source1() As String
            Get
                Return CType(Me("Chemin_Source1"),String)
            End Get
            Set
                Me("Chemin_Source1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 128, 192")>  _
        Public Property Couleur_Recherche_Simplifiée() As Global.System.Drawing.Color
            Get
                Return CType(Me("Couleur_Recherche_Simplifiée"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Couleur_Recherche_Simplifiée") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255, 62, 158")>  _
        Public Property Couleur_Recherche_Guidée() As Global.System.Drawing.Color
            Get
                Return CType(Me("Couleur_Recherche_Guidée"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Couleur_Recherche_Guidée") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("255, 255, 192")>  _
        Public Property Couleur_Recherche_Statistique() As Global.System.Drawing.Color
            Get
                Return CType(Me("Couleur_Recherche_Statistique"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Couleur_Recherche_Statistique") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("128, 128, 255")>  _
        Public Property Couleur_Recherche_Avancee() As Global.System.Drawing.Color
            Get
                Return CType(Me("Couleur_Recherche_Avancee"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Couleur_Recherche_Avancee") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property COLOR1() As Global.System.Drawing.Color
            Get
                Return CType(Me("COLOR1"),Global.System.Drawing.Color)
            End Get
            Set
                Me("COLOR1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Nom_de_la_connexion() As String
            Get
                Return CType(Me("Nom_de_la_connexion"),String)
            End Get
            Set
                Me("Nom_de_la_connexion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Utiliser_toujours_cette_connexion() As String
            Get
                Return CType(Me("Utiliser_toujours_cette_connexion"),String)
            End Get
            Set
                Me("Utiliser_toujours_cette_connexion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Activation_Synthese_Vocale() As Boolean
            Get
                Return CType(Me("Activation_Synthese_Vocale"),Boolean)
            End Get
            Set
                Me("Activation_Synthese_Vocale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property Langue_logiciel() As Integer
            Get
                Return CType(Me("Langue_logiciel"),Integer)
            End Get
            Set
                Me("Langue_logiciel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Modification_Objet() As Boolean
            Get
                Return CType(Me("Modification_Objet"),Boolean)
            End Get
            Set
                Me("Modification_Objet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RA_Référence_à_ajouter() As String
            Get
                Return CType(Me("RA_Référence_à_ajouter"),String)
            End Get
            Set
                Me("RA_Référence_à_ajouter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Verrouillage_Script() As Boolean
            Get
                Return CType(Me("Verrouillage_Script"),Boolean)
            End Get
            Set
                Me("Verrouillage_Script") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Debugage_SCRIPT() As Boolean
            Get
                Return CType(Me("Debugage_SCRIPT"),Boolean)
            End Get
            Set
                Me("Debugage_SCRIPT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RS_Référence_à_ajouter() As String
            Get
                Return CType(Me("RS_Référence_à_ajouter"),String)
            End Get
            Set
                Me("RS_Référence_à_ajouter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Timer3_RS_MOTS_CLEFS() As Boolean
            Get
                Return CType(Me("Timer3_RS_MOTS_CLEFS"),Boolean)
            End Get
            Set
                Me("Timer3_RS_MOTS_CLEFS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Mots_clefs_à_ajouter() As String
            Get
                Return CType(Me("Mots_clefs_à_ajouter"),String)
            End Get
            Set
                Me("Mots_clefs_à_ajouter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageRs() As Integer
            Get
                Return CType(Me("TypeMessageRs"),Integer)
            End Get
            Set
                Me("TypeMessageRs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageErreurRs() As String
            Get
                Return CType(Me("MessageErreurRs"),String)
            End Get
            Set
                Me("MessageErreurRs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageRa() As Integer
            Get
                Return CType(Me("TypeMessageRa"),Integer)
            End Get
            Set
                Me("TypeMessageRa") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageErreurRa() As String
            Get
                Return CType(Me("MessageErreurRa"),String)
            End Get
            Set
                Me("MessageErreurRa") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageRg() As Integer
            Get
                Return CType(Me("TypeMessageRg"),Integer)
            End Get
            Set
                Me("TypeMessageRg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageErreurRg() As String
            Get
                Return CType(Me("MessageErreurRg"),String)
            End Get
            Set
                Me("MessageErreurRg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageDetailsEnregistrementW1() As Integer
            Get
                Return CType(Me("TypeMessageDetailsEnregistrementW1"),Integer)
            End Get
            Set
                Me("TypeMessageDetailsEnregistrementW1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageErreurDetailsEnregistrementW1() As String
            Get
                Return CType(Me("MessageErreurDetailsEnregistrementW1"),String)
            End Get
            Set
                Me("MessageErreurDetailsEnregistrementW1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PageHtmlRS() As String
            Get
                Return CType(Me("PageHtmlRS"),String)
            End Get
            Set
                Me("PageHtmlRS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PageHtmlRA() As String
            Get
                Return CType(Me("PageHtmlRA"),String)
            End Get
            Set
                Me("PageHtmlRA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PageHtmlRG() As String
            Get
                Return CType(Me("PageHtmlRG"),String)
            End Get
            Set
                Me("PageHtmlRG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PageHtmlDetailsEnregistrementW1() As String
            Get
                Return CType(Me("PageHtmlDetailsEnregistrementW1"),String)
            End Get
            Set
                Me("PageHtmlDetailsEnregistrementW1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PageHtmlDetailsEnregistrementW2() As String
            Get
                Return CType(Me("PageHtmlDetailsEnregistrementW2"),String)
            End Get
            Set
                Me("PageHtmlDetailsEnregistrementW2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PageHtmlDetailsEnregistrementW3() As String
            Get
                Return CType(Me("PageHtmlDetailsEnregistrementW3"),String)
            End Get
            Set
                Me("PageHtmlDetailsEnregistrementW3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageDetailsEnregistrementW3() As Integer
            Get
                Return CType(Me("TypeMessageDetailsEnregistrementW3"),Integer)
            End Get
            Set
                Me("TypeMessageDetailsEnregistrementW3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageErreurDetailsEnregistrementW2() As String
            Get
                Return CType(Me("MessageErreurDetailsEnregistrementW2"),String)
            End Get
            Set
                Me("MessageErreurDetailsEnregistrementW2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PageHtmlGestionBase() As String
            Get
                Return CType(Me("PageHtmlGestionBase"),String)
            End Get
            Set
                Me("PageHtmlGestionBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageErreurGestionBase() As String
            Get
                Return CType(Me("MessageErreurGestionBase"),String)
            End Get
            Set
                Me("MessageErreurGestionBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageGestionBase() As Integer
            Get
                Return CType(Me("TypeMessageGestionBase"),Integer)
            End Get
            Set
                Me("TypeMessageGestionBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property GestionBaseRechercheDataTable() As Global.System.Data.DataTable
            Get
                Return CType(Me("GestionBaseRechercheDataTable"),Global.System.Data.DataTable)
            End Get
            Set
                Me("GestionBaseRechercheDataTable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ResultatGestionBaseNbreParPage() As Integer
            Get
                Return CType(Me("ResultatGestionBaseNbreParPage"),Integer)
            End Get
            Set
                Me("ResultatGestionBaseNbreParPage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ResultatGestionBaseNumeroPage() As Integer
            Get
                Return CType(Me("ResultatGestionBaseNumeroPage"),Integer)
            End Get
            Set
                Me("ResultatGestionBaseNumeroPage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PageHtmlAjoutCompteGestionBase() As String
            Get
                Return CType(Me("PageHtmlAjoutCompteGestionBase"),String)
            End Get
            Set
                Me("PageHtmlAjoutCompteGestionBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageAjoutCompteGestionBase() As String
            Get
                Return CType(Me("MessageAjoutCompteGestionBase"),String)
            End Get
            Set
                Me("MessageAjoutCompteGestionBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageAjoutCompteGestionBase() As Integer
            Get
                Return CType(Me("TypeMessageAjoutCompteGestionBase"),Integer)
            End Get
            Set
                Me("TypeMessageAjoutCompteGestionBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageAuthentificationtCompteGestionBase() As String
            Get
                Return CType(Me("MessageAuthentificationtCompteGestionBase"),String)
            End Get
            Set
                Me("MessageAuthentificationtCompteGestionBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageAuthentificationtCompteGestionBase() As Integer
            Get
                Return CType(Me("TypeMessageAuthentificationtCompteGestionBase"),Integer)
            End Get
            Set
                Me("TypeMessageAuthentificationtCompteGestionBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageRécupérationCompteGestionBase() As String
            Get
                Return CType(Me("MessageRécupérationCompteGestionBase"),String)
            End Get
            Set
                Me("MessageRécupérationCompteGestionBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageRécupérationCompteGestionBase() As Integer
            Get
                Return CType(Me("TypeMessageRécupérationCompteGestionBase"),Integer)
            End Get
            Set
                Me("TypeMessageRécupérationCompteGestionBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RécupérationNomCompteGestionBase() As String
            Get
                Return CType(Me("RécupérationNomCompteGestionBase"),String)
            End Get
            Set
                Me("RécupérationNomCompteGestionBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RécupérationMotdePasseCompteGestionBase() As String
            Get
                Return CType(Me("RécupérationMotdePasseCompteGestionBase"),String)
            End Get
            Set
                Me("RécupérationMotdePasseCompteGestionBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageSupprimerCompteGestionBase() As Integer
            Get
                Return CType(Me("TypeMessageSupprimerCompteGestionBase"),Integer)
            End Get
            Set
                Me("TypeMessageSupprimerCompteGestionBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageSupprimerCompteGestionBase() As String
            Get
                Return CType(Me("MessageSupprimerCompteGestionBase"),String)
            End Get
            Set
                Me("MessageSupprimerCompteGestionBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageSupprimerEnregistrement() As Integer
            Get
                Return CType(Me("TypeMessageSupprimerEnregistrement"),Integer)
            End Get
            Set
                Me("TypeMessageSupprimerEnregistrement") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageSupprimerEnregistrement() As String
            Get
                Return CType(Me("MessageSupprimerEnregistrement"),String)
            End Get
            Set
                Me("MessageSupprimerEnregistrement") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageAjoutEnregistrement() As Integer
            Get
                Return CType(Me("TypeMessageAjoutEnregistrement"),Integer)
            End Get
            Set
                Me("TypeMessageAjoutEnregistrement") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageAjoutEnregistrement() As String
            Get
                Return CType(Me("MessageAjoutEnregistrement"),String)
            End Get
            Set
                Me("MessageAjoutEnregistrement") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageAjoutTreeviewPosition() As Integer
            Get
                Return CType(Me("TypeMessageAjoutTreeviewPosition"),Integer)
            End Get
            Set
                Me("TypeMessageAjoutTreeviewPosition") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageAjoutTreeviewPosition() As String
            Get
                Return CType(Me("MessageAjoutTreeviewPosition"),String)
            End Get
            Set
                Me("MessageAjoutTreeviewPosition") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageAjoutLiensRéférences() As Integer
            Get
                Return CType(Me("TypeMessageAjoutLiensRéférences"),Integer)
            End Get
            Set
                Me("TypeMessageAjoutLiensRéférences") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageAjoutLiensRéférences() As String
            Get
                Return CType(Me("MessageAjoutLiensRéférences"),String)
            End Get
            Set
                Me("MessageAjoutLiensRéférences") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageSupprimeLiensRéférences() As Integer
            Get
                Return CType(Me("TypeMessageSupprimeLiensRéférences"),Integer)
            End Get
            Set
                Me("TypeMessageSupprimeLiensRéférences") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageSupprimeLiensRéférences() As String
            Get
                Return CType(Me("MessageSupprimeLiensRéférences"),String)
            End Get
            Set
                Me("MessageSupprimeLiensRéférences") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MaintenanceTransfertIdealtake() As Boolean
            Get
                Return CType(Me("MaintenanceTransfertIdealtake"),Boolean)
            End Get
            Set
                Me("MaintenanceTransfertIdealtake") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageChargementEnregistrement() As Integer
            Get
                Return CType(Me("TypeMessageChargementEnregistrement"),Integer)
            End Get
            Set
                Me("TypeMessageChargementEnregistrement") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageChargementEnregistrement() As String
            Get
                Return CType(Me("MessageChargementEnregistrement"),String)
            End Get
            Set
                Me("MessageChargementEnregistrement") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageMiseàJourEnregistrement() As Integer
            Get
                Return CType(Me("TypeMessageMiseàJourEnregistrement"),Integer)
            End Get
            Set
                Me("TypeMessageMiseàJourEnregistrement") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageMiseàJourEnregistrement() As String
            Get
                Return CType(Me("MessageMiseàJourEnregistrement"),String)
            End Get
            Set
                Me("MessageMiseàJourEnregistrement") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AjoutFireWallException() As Boolean
            Get
                Return CType(Me("AjoutFireWallException"),Boolean)
            End Get
            Set
                Me("AjoutFireWallException") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("server=localhost;User Id=root;database=test080")>  _
        Public ReadOnly Property Mysql_ConnectionString() As String
            Get
                Return CType(Me("Mysql_ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TypeMessageDetailsEnregistrementW2() As Integer
            Get
                Return CType(Me("TypeMessageDetailsEnregistrementW2"),Integer)
            End Get
            Set
                Me("TypeMessageDetailsEnregistrementW2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageErreurDetailsEnregistrementW3() As String
            Get
                Return CType(Me("MessageErreurDetailsEnregistrementW3"),String)
            End Get
            Set
                Me("MessageErreurDetailsEnregistrementW3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AuthentificationGestionBase() As Boolean
            Get
                Return CType(Me("AuthentificationGestionBase"),Boolean)
            End Get
            Set
                Me("AuthentificationGestionBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ActivationAdresseLocale() As Boolean
            Get
                Return CType(Me("ActivationAdresseLocale"),Boolean)
            End Get
            Set
                Me("ActivationAdresseLocale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AdresseLocale() As String
            Get
                Return CType(Me("AdresseLocale"),String)
            End Get
            Set
                Me("AdresseLocale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DerniersRésultatsRS() As Global.System.Data.DataTable
            Get
                Return CType(Me("DerniersRésultatsRS"),Global.System.Data.DataTable)
            End Get
            Set
                Me("DerniersRésultatsRS") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property DerniersRésultatsRA() As Global.System.Data.DataTable
            Get
                Return CType(Me("DerniersRésultatsRA"), Global.System.Data.DataTable)
            End Get
            Set(value As Global.System.Data.DataTable)
                Me("DerniersRésultatsRA") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property DerniersRésultatsRG() As Global.System.Data.DataTable
            Get
                Return CType(Me("DerniersRésultatsRG"), Global.System.Data.DataTable)
            End Get
            Set(value As Global.System.Data.DataTable)
                Me("DerniersRésultatsRG") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property MotifArbreFullPath() As String
            Get
                Return CType(Me("MotifArbreFullPath"), String)
            End Get
            Set(value As String)
                Me("MotifArbreFullPath") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.IDEALTAKE.My.MySettings
            Get
                Return Global.IDEALTAKE.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
